services:
  - docker

jobs:
  include:
    - stage: Build node-backend image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t node-backend ./node-backend
        - docker images
        - docker tag node-backend $DOCKER_USERNAME/node-backend
        - docker push $DOCKER_USERNAME/node-backend
    - stage: Build frontend image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t frontend ./frontend
        - docker images
        - docker tag frontend $DOCKER_USERNAME/frontend
        - docker push $DOCKER_USERNAME/frontend