apiVersion: v1
kind: Service
metadata:
   name: node-backend-service
   labels:
     app: node-backend-service
spec:
   ports:
     - protocol: TCP
       port: 3000
       targetPort: 3000
   selector:
     app: node-backend-pod