apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth-pod
  template:
    metadata:
      name: auth-pod
      labels:
        app: auth-pod
    spec:
      containers:
        - name: auth-container
          image: vidarhun/auth
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31080
  selector:
    app: auth-pod